In [ ]:
import numpy as np
from catboost import CatBoostClassifier, Pool

In [ ]:
import random
def RandomPermutation():
    perm = list(range(8))
    random.shuffle(perm)
    return perm

In [ ]:
def StupidPermutation():
    partialSums = [0,1,8,35,111,285,
        628,1230,2191,3606,5546,8039,11056,14506,18242,
        22078,25814,29264,32281,34774,36714,38129,39090,
        39692,40035,40209,40285,40312,40319,40320]
    r = random.randint(0, partialSums[-1])
    numInv = 0
    while partialSums[numInv] < r:
        numInv += 1
    perm = list(range(8))
    for step in range(numInv):
        t1 = random.randint(0, 7)
        t2 = random.randint(0, 7)
        perm[t1], perm[t2] = perm[t2], perm[t1]
    return perm

In [ ]:
from tqdm import tqdm

In [ ]:
# each object has 64 features - flatten 8x8 matrix of counting how many times each digin from 0 to 7 was on each place on 1000 permutations
def generate_sample(size):
  x = []
  y = []
  for i in tqdm(range(size)):
    label = random.randint(0, 1)
    perm = np.zeros((8, 8))
    if label == 1:
      for i in range(1000):
        sample = RandomPermutation()
        for i in range(8):
          perm[i][sample[i]] += 1
    else:
      for i in range(1000):
        sample = StupidPermutation()
        for i in range(8):
          perm[i][sample[i]] += 1
    x.append(perm.flatten())
    y.append(label)
  return np.array(x), np.array(y)

In [ ]:
x_train, y_train = generate_sample(1000)

100%|██████████| 1000/1000 [00:26<00:00, 37.40it/s]


In [ ]:
x_test, y_test = generate_sample(200)

100%|██████████| 200/200 [00:05<00:00, 33.98it/s]


In [ ]:
x_train

<function ndarray.flatten>

In [ ]:
y_train

array([0, 1, 1, ..., 1, 0, 1])

In [ ]:
model = CatBoostClassifier(iterations=5,
                           depth=5,
                           learning_rate=0.5,
                           loss_function='Logloss',
                           verbose=True)

In [ ]:
model.fit(x_train, y_train)

0:	learn: 0.2417054	total: 5.7ms	remaining: 22.8ms
1:	learn: 0.1001320	total: 9.72ms	remaining: 14.6ms
2:	learn: 0.0626111	total: 13.1ms	remaining: 8.7ms
3:	learn: 0.0326931	total: 16.3ms	remaining: 4.09ms
4:	learn: 0.0232769	total: 19.6ms	remaining: 0us


In [ ]:
test_data = catboost_pool = Pool(x_train,
                                 y_train)

In [ ]:
preds_class = model.predict(x_test)

In [ ]:
preds_class

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1])

In [ ]:
y_test

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1])

In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score

In [ ]:
accuracy_score(y_test, preds_class)

0.995

In [ ]:
roc_auc_score(y_test, np.array(pr))

0.419877890101091

In [ ]:
model.score(test_data)

0.95

In [ ]:
test_data

In [ ]:
f = open("./permutations.in", "r")
lines = []
for line in f:
  lines.append(list(map(int, line.strip().split())))

In [ ]:
x_pr = []
for i in tqdm(range(200)):
  perm = np.zeros((8, 8))
  for j in range(1000):
    for k in range(8):
      perm[k][lines[i * 1000 + j + 1][k]] += 1
  x_pr.append(perm.flatten())

100%|██████████| 200/200 [00:04<00:00, 44.44it/s]


In [ ]:
x_pr

[array([123., 130., 117., 122., 141., 132., 112., 123., 116., 133., 112.,
        129., 126., 133., 129., 122., 143., 134., 134., 122., 118., 107.,
        120., 122., 112., 116., 124., 119., 123., 139., 136., 131., 141.,
        111., 133., 126., 129., 112., 111., 137., 119., 142., 116., 121.,
        125., 121., 128., 128., 127., 111., 146., 130., 108., 126., 139.,
        113., 119., 123., 118., 131., 130., 130., 125., 124.]),
 array([154., 115., 129., 120., 108., 130., 112., 132., 114., 142., 124.,
        111., 112., 120., 135., 142.,  91., 137., 131., 143., 119., 142.,
        121., 116., 126., 117., 124., 145., 118., 114., 124., 132., 115.,
        127., 126., 132., 143., 112., 127., 118., 140., 115., 118., 112.,
        124., 155., 110., 126., 111., 128., 126., 122., 142., 113., 150.,
        108., 149., 119., 122., 115., 134., 114., 121., 126.]),
 array([131., 125., 142., 122., 122., 119., 123., 116., 138., 126.,  98.,
        127., 129., 110., 138., 134., 129., 132., 133., 11

In [ ]:
y_pr = model.predict(x_pr)

In [ ]:
y_pr

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1])

In [ ]:
for i in range(200):
  if y_pr[i] == 1:
    print(i)

0
2
3
4
5
6
10
14
15
17
18
26
29
31
32
33
34
37
39
41
42
43
44
47
48
50
51
53
55
57
60
62
63
64
66
67
68
70
71
74
79
81
82
88
90
91
92
96
104
106
110
111
113
114
115
117
118
119
120
125
126
131
132
134
136
137
139
140
141
144
145
147
149
150
151
152
157
158
161
162
164
167
168
170
172
173
174
176
179
183
184
186
189
190
192
193
197
199


In [ ]:
for i in range(200):
  if y_pr[i] == 0:
    print(i)

1
7
8
9
11
12
13
16
19
20
21
22
23
24
25
27
28
30
35
36
38
40
45
46
49
52
54
56
58
59
61
65
69
72
73
75
76
77
78
80
83
84
85
86
87
89
93
94
95
97
98
99
100
101
102
103
105
107
108
109
112
116
121
122
123
124
127
128
129
130
133
135
138
142
143
146
148
153
154
155
156
159
160
163
165
166
169
171
175
177
178
180
181
182
185
187
188
191
194
195
196
198
