In [63]:
n = int(input())
xy = []
for i in range(n):
    x, y = map(int, input().split())
    xy.append([x, y])
xy.sort()
xy

[[0, 1], [1, 1], [2, 0], [3, 0]]

In [73]:
def calc_loss(n, y, y_true):
    loss = 0
    for i in range(n):
        loss += (y[i] - y_true[i]) ** 2
    loss /= n
    loss = loss ** 0.5
    return loss


In [74]:
def f(a, b, t, x):
    y = []
    for i in x:
        y.append(a if i < t else b)
    return y

In [81]:
import numpy as np
arr = np.array(xy)
x = arr[:, 0]
y = arr[:, 1]
b = np.mean(y)
a = 0
opta, optb, optt = 0, 0, 0
minloss = 10000000000

asq = 0
bsq = np.sum(np.square(y)) / n

for c in range(n - 1):
    t = (x[c] + x[c + 1]) / 2

    asq *= c
    asq += y[c] ** 2
    asq /= (c + 1)
    bsq *= (n - c)
    bsq -= y[c] ** 2
    bsq /= (n - c - 1)

    a *= c
    a += y[c]
    a /= (c + 1)
    b *= (n - c)
    b -= y[c]
    b /= (n - c - 1)
    # a = np.mean(y[:c + 1])
    # b = np.mean(y[c + 1:])
    loss = ((asq - a ** 2) * (c + 1) + (bsq - b ** 2) * (n - c - 1)) / n
    loss = loss ** 0.5
    if loss < minloss:
        opta, optb, optt = a, b, t
        minloss = loss
t = x[0] - 1
a = np.mean(y)
b = a
loss = calc_loss(n, f(a, b, t, x), y)
if loss < minloss:
    opta, optb, optt = a, b, t
    minloss = loss
print(opta, optb, optt)

0.5
0.3333333333333333 0.5
0.0 1.5
0.0 2.5
1.0 0.0 1.5


In [76]:
np.mean(arr[:, 1][4:])

/home/alexp/.local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alexp/.local/lib/python3.10/site-packages/numpy/_core/_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


np.float64(nan)

In [51]:
calc_loss(n, f(1, 0, 1.5, x), y)

np.float64(0.0)

In [43]:
arr[:, 1][:1 + 1]

array([1, 1])

In [42]:
arr[:, 1][1 + 1:]

array([0, 0])

In [62]:
y[0:]

array([1])

In [72]:
a = np.array([1, 2, 3])
np.sum(np.square(a))

np.int64(14)

In [87]:
np.unique(np.array([[1, 1], [1, 11], [2, 1], [3, 2], [2, 3]]), axis=1)

array([[ 1,  1],
       [ 1, 11],
       [ 2,  1],
       [ 3,  2],
       [ 2,  3]])